// <auto-generated />
namespace PolkuForum.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Title : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Title));
        
        string IMigrationMetadata.Id
        {
            get { return "201702271818113_Title"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
